using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("NetBpm.Web for Microsoft .NET Framework 1.1")]
[assembly: AssemblyDescriptionAttribute("NetBpm web application.")]
[assembly: AssemblyCompanyAttribute("NetBpm.org")]
[assembly: AssemblyProductAttribute("NetBpm.Web")]
[assembly: AssemblyCopyrightAttribute("Licensed under Apache License, Version 2.0.")]
[assembly: AssemblyVersionAttribute("0.8.3.1")]
[assembly: AssemblyInformationalVersionAttribute("0.8")]
[assembly: AssemblyFileVersionAttribute("0.8.3.1")]

